package:
  name: "datasail"
  version: "0.1.0"

source:
  # git_url: https://github.com/kalininalab/DataSAIL.git
  # git_rev: main
  path: ./..

build:
  entry_points:
    - datasail = datasail.__main__:main
  script: python setup.py install
  # preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python
    - numpy
    - pandas
    - networkx
    - matplotlib
    - pytest
    - setuptools
    - pyscipopt
    - scikit-learn
    - foldseek
    - mmseqs2
    - cd-hit
    - mash
    - tmalign
    - mosek
    - cvxpy
    - pytest-cov
    - rdkit>=2023.03.3
    - pytest-cases
    - pyyaml

about:
  home: https://github.com/kalininalab/DataSAIL
  license: MIT
  license_file: LICENSE
  summary: DataSAIL is a tool to split datasets while reducing information leakage.
