# This is a basic workflow to help you get started with Actions

name: Test installation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - dev
      - dev_cicd
  pull_request:
    branches:
      - main
      - dev
      - dev_cicd
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: macos-latest
          - os: ubuntu-latest

    runs-on: ${{ matrix.cfg.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: datasail
          use-mamba: true

      - name: Install DataSAIL
        shell: bash -l {0}
        run: |
          mamba install -c mosek -c conda-forge -c bioconda -c kalininalab -y datasail
          pip install grakel

      - name: Test installation
        shell: bash -l {0}
        run: datasail -h
