package:
  name: "datasail"
  version: "0.0.4"

source:
  git_url: https://github.com/kalininalab/DataSAIL.git
  git_rev: main

build:
  entry_points:
    - datasail = datasail.sail:datasail

requirements:
  host:
    - python==3.10
    - setuptools
    - setuptools_scm
    - pip
  build:
    - python==3.10
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python==3.10
    - numpy
    - pandas
    - networkx
    - matplotlib
    - pytest
    - setuptools
    - pyscipopt
    - foldseek
    - mmseqs2
    - cd-hit
    - mash
    - tmalign
    - mosek
    - cvxpy
    - pytest-cov
    - rdkit
    - pytest-cases

about:
  home: https://github.com/kalininalab/DataSAIL
  license: MIT
  license_file: LICENSE
  summary: DataSAIL is a tool to split datasets while reducing information leakage.
