name: publish_conda

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  publish:
    strategy:
      matrix:
        py: ['3.8', '3.9', '3.10']
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: Old-Shatterhand/publish-conda-multichannel-action@v0.0.6
      with:
        AnacondaToken: ${{ secrets.DATASAIL_ANACONDA_TOKEN }}
        Channels: "mosek"
        Versions: ${{ matrix.version }}
