# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - dev
      - dev_cicd
  pull_request:
    branches:
      - main
      - dev
      - dev_cicd

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          miniforge-version: latest
          activate-environment: scala
          
      - name: Update environment
        shell: bash -l {0}
        run: |
          conda install -c conda-forge -y numpy pandas networkx matplotlib pytest setuptools pyscipopt 
          pip install grakel cvxpy rdkit pytest-cov
        
      - name: Run tests
        shell: bash -l {0}
        run: |
          cd tests
          pytest -m "not todo" --cov=../scala/ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          version: "v0.1.15"
          fail_ci_if_error: true
          files: coverage.xml
